import type { NodeDefinition } from '../types/nodes';

export const NODE_DEFINITIONS: NodeDefinition[] = [
  // Sources
  {
    type: 'marketPair',
    label: 'Market Pair',
    category: 'source',
    icon: '💱',
    description: 'Select a forex pair (MT5)',
    premium: false,
    inputs: [],
    outputs: ['data'],
    defaultData: { pair: 'EURUSD' },
  },
  {
    type: 'chartSource',
    label: 'Chart Source',
    category: 'source',
    icon: '📊',
    description: 'OHLCV candle data',
    premium: false,
    inputs: ['market'],
    outputs: ['candles'],
    defaultData: { timeframe: 'H1' },
  },
  {
    type: 'newsFeed',
    label: 'News Feed',
    category: 'source',
    icon: '📰',
    description: 'Forex news & headlines',
    premium: false,
    inputs: [],
    outputs: ['news'],
    defaultData: {},
  },
  {
    type: 'economicCalendar',
    label: 'Economic Calendar',
    category: 'source',
    icon: '📅',
    description: 'NFP, FOMC, ECB, BOJ events',
    premium: false,
    inputs: [],
    outputs: ['events'],
    defaultData: {},
  },

  // Analysis
  {
    type: 'technicalIndicator',
    label: 'Technical Indicators',
    category: 'analysis',
    icon: '📈',
    description: 'RSI, MACD, Bollinger, EMA, SMA',
    premium: false,
    inputs: ['candles'],
    outputs: ['signals'],
    defaultData: { indicators: ['RSI', 'MACD', 'Bollinger Bands'] },
  },
  {
    type: 'chartPattern',
    label: 'Chart Patterns',
    category: 'analysis',
    icon: '🔍',
    description: 'Double Top, H&S, Triangle detection',
    premium: false,
    inputs: ['candles'],
    outputs: ['patterns'],
    defaultData: { patterns: ['Head & Shoulders', 'Double Top', 'Triangle'] },
  },
  {
    type: 'sentiment',
    label: 'Sentiment Analysis',
    category: 'analysis',
    icon: '🧠',
    description: 'Fear & Greed, social sentiment',
    premium: false,
    inputs: ['news'],
    outputs: ['sentiment'],
    defaultData: {},
  },
  {
    type: 'fundamental',
    label: 'Fundamental Analysis',
    category: 'analysis',
    icon: '🏦',
    description: 'Interest rates, GDP, CPI data',
    premium: false,
    inputs: ['events'],
    outputs: ['analysis'],
    defaultData: {},
  },
  {
    type: 'psychProfile',
    label: 'Risk Profile',
    category: 'analysis',
    icon: '🎯',
    description: 'Trading style & risk tolerance',
    premium: false,
    inputs: [],
    outputs: ['profile'],
    defaultData: { riskTolerance: 'moderate', style: 'swing' },
  },

  {
    type: 'stockAnalysis',
    label: 'Stock Analyzer',
    category: 'analysis',
    icon: '🏛️',
    description: 'P/E, FCF, EBITDA, multiples',
    premium: false,
    inputs: ['data'],
    outputs: ['analysis'],
    defaultData: { ticker: 'SBER' },
  },
  {
    type: 'reportSelector',
    label: 'Report Type',
    category: 'analysis',
    icon: '📊',
    description: 'RAS vs IFRS — which report for what',
    premium: false,
    inputs: ['data'],
    outputs: ['report'],
    defaultData: {},
  },
  {
    type: 'cashFlow',
    label: 'Cash Flow',
    category: 'analysis',
    icon: '💰',
    description: 'FCF, EBITDA, CAPEX, LTM',
    premium: false,
    inputs: ['data'],
    outputs: ['cashflow'],
    defaultData: {},
  },
  {
    type: 'debtAnalysis',
    label: 'Debt Analysis',
    category: 'analysis',
    icon: '📉',
    description: 'Debt load & stress test',
    premium: false,
    inputs: ['data'],
    outputs: ['debt'],
    defaultData: {},
  },
  {
    type: 'sectorCompare',
    label: 'Sector Compare',
    category: 'analysis',
    icon: '🏭',
    description: 'Best company in the sector',
    premium: false,
    inputs: ['data'],
    outputs: ['sector'],
    defaultData: {},
  },
  {
    type: 'profitability',
    label: 'Profitability',
    category: 'analysis',
    icon: '📈',
    description: 'ROE, ROA, margin analysis',
    premium: false,
    inputs: ['data'],
    outputs: ['profit'],
    defaultData: {},
  },
  {
    type: 'dividendCapture',
    label: 'Dividend Capture',
    category: 'analysis',
    icon: '💎',
    description: 'Dividend yield, ex-date, payout',
    premium: false,
    inputs: ['data'],
    outputs: ['dividends'],
    defaultData: {},
  },
  {
    type: 'eventRepricing',
    label: 'Event Repricing',
    category: 'analysis',
    icon: '📰',
    description: 'Repricing after earnings & events',
    premium: false,
    inputs: ['data'],
    outputs: ['events'],
    defaultData: {},
  },
  {
    type: 'tradingStyle',
    label: 'Trading Style',
    category: 'agent',
    icon: '🎯',
    description: 'Scalping, swing, or long-term',
    premium: false,
    inputs: ['analysis'],
    outputs: ['style'],
    defaultData: { tradingStyle: 'swing' },
  },
  {
    type: 'portfolioScore',
    label: 'Portfolio Score',
    category: 'output',
    icon: '🎯',
    description: 'Final score: buy or skip',
    premium: false,
    inputs: ['analysis', 'cashflow', 'debt', 'sector', 'profit'],
    outputs: [],
    defaultData: {},
  },

  // ─── Crypto ──────────────────────────────────────
  {
    type: 'cryptoSource',
    label: 'Crypto Pair',
    category: 'source',
    icon: '₿',
    description: 'Binance crypto pairs (BTC, ETH, SOL...)',
    premium: false,
    inputs: [],
    outputs: ['data'],
    defaultData: { pair: 'BTCUSDT' },
  },
  {
    type: 'cryptoAsset',
    label: 'Crypto Asset',
    category: 'source',
    icon: '₿',
    description: '5 supported USDT pairs — price, 24h, mkt cap',
    premium: false,
    inputs: [],
    outputs: ['data'],
    defaultData: { pair: 'BTCUSDT', weight: 1.0 },
  },
  {
    type: 'cryptoTechnical',
    label: 'Crypto Technical',
    category: 'analysis',
    icon: '📊',
    description: 'RSI, MACD, BB on Binance candles (live)',
    premium: false,
    inputs: ['data'],
    outputs: ['signals'],
    defaultData: { indicators: ['RSI', 'MACD', 'Bollinger Bands'], interval: '1h', weight: 1.0 },
  },
  {
    type: 'cryptoFundamental',
    label: 'Crypto Fundamental',
    category: 'analysis',
    icon: '📰',
    description: 'News: macro + geopolitics + crypto sentiment (Finnhub + RSS)',
    premium: false,
    inputs: ['data'],
    outputs: ['signals'],
    defaultData: { categories: ['macro', 'geopolitics', 'regulation'], hours: 24, weight: 1.0 },
  },
  {
    type: 'cryptoScanner',
    label: 'Altcoin Scanner',
    category: 'analysis',
    icon: '🔍',
    description: 'Top-5 dips: volume spikes, RSI dips, price drops',
    premium: false,
    inputs: ['candles'],
    outputs: ['signals'],
    defaultData: { scanMode: ['volume_spike', 'rsi_dip'], thresholds: { volumeMultiplier: 2.5, rsiOversold: 30, dipPercent: 5 }, weight: 1.0 },
  },
  {
    type: 'onChainMetrics',
    label: 'On-Chain Metrics',
    category: 'analysis',
    icon: '⛓️',
    description: 'Whale activity, exchange flows',
    premium: false,
    inputs: ['data'],
    outputs: ['metrics'],
    defaultData: { metrics: ['whale_activity', 'exchange_inflow'] },
  },
  {
    // Legacy TF.js local inference — superseded by cryptoML (Patch 2C). Component kept for existing templates.
    type: 'mlPredictor',
    label: 'ML Predictor',
    category: 'agent',
    icon: '🧠',
    description: 'TensorFlow.js price prediction',
    premium: false,
    hidden: true,
    inputs: ['signals', 'candles'],
    outputs: ['prediction'],
    defaultData: { modelStatus: 'idle', features: ['RSI', 'MACD', 'Volume', 'Volatility', 'Momentum', 'BB Position'] },
  },
  {
    type: 'cryptoML',
    label: 'Crypto ML',
    category: 'agent',
    icon: '🧠',
    description: 'Ensemble XGB+LGBM+RF + k-NN similar situations',
    premium: false,
    inputs: ['tech', 'news', 'style'],
    outputs: ['prediction'],
    defaultData: { weight: 1.0 },
  },

  // Logic
  {
    type: 'condition',
    label: 'Condition',
    category: 'logic',
    icon: '⚡',
    description: 'If/then rules',
    premium: false,
    inputs: ['signals'],
    outputs: ['trigger'],
    defaultData: { indicator: 'RSI', operator: '>', value: 70 },
  },
  {
    type: 'combiner',
    label: 'Combiner',
    category: 'logic',
    icon: '🔗',
    description: 'AND / OR logic',
    premium: false,
    inputs: ['input1', 'input2'],
    outputs: ['combined'],
    defaultData: { logic: 'AND' },
  },

  // AI Agents
  {
    type: 'tradingAnalyst',
    label: 'Trading Analyst',
    category: 'agent',
    icon: '🤖',
    description: 'AI analyzes all inputs',
    premium: false,
    inputs: ['signals', 'news', 'patterns'],
    outputs: ['analysis'],
    defaultData: { prompt: 'Analyze the current market conditions' },
  },
  {
    type: 'riskManager',
    label: 'Risk Manager',
    category: 'agent',
    icon: '🛡️',
    description: 'AI risk assessment',
    premium: false,
    inputs: ['analysis', 'profile'],
    outputs: ['risk'],
    defaultData: { prompt: 'Evaluate risk for this strategy' },
  },
  {
    type: 'guidedTrader',
    label: 'Guided AI',
    category: 'agent',
    icon: '🎓',
    description: 'Explains WHY — for beginners',
    premium: false,
    inputs: ['signals', 'news'],
    outputs: ['analysis'],
    defaultData: { level: 'beginner' },
  },
  {
    type: 'riskCap',
    label: 'Risk Cap',
    category: 'agent',
    icon: '🔥',
    description: 'Daily loss & trade limits',
    premium: false,
    inputs: ['analysis'],
    outputs: ['risk'],
    defaultData: { maxDailyLoss: 500, maxPositionSize: 0.5, maxTradesPerDay: 10 },
  },

  // Output
  {
    type: 'dashboard',
    label: 'Dashboard',
    category: 'output',
    icon: '📋',
    description: 'Visual output & signals',
    premium: false,
    inputs: ['analysis', 'risk'],
    outputs: [],
    defaultData: { widgets: ['gauge', 'signals', 'chart'] },
  },
];

export const CATEGORY_LABELS: Record<string, { label: string; color: string }> = {
  source: { label: 'Sources', color: '#3b82f6' },
  analysis: { label: 'Analysis', color: '#10b981' },
  logic: { label: 'Logic', color: '#f59e0b' },
  agent: { label: 'AI Agents', color: '#a855f7' },
  output: { label: 'Output', color: '#ef4444' },
};
