import type { NodeDefinition } from '../types/nodes';

export const NODE_DEFINITIONS: NodeDefinition[] = [
  // Sources
  {
    type: 'marketPair',
    label: 'Market Pair',
    category: 'source',
    icon: '💱',
    description: 'Select a forex pair (MT5)',
    premium: false,
    inputs: [],
    outputs: ['data'],
    defaultData: { pair: 'EURUSD' },
  },
  {
    type: 'chartSource',
    label: 'Chart Source',
    category: 'source',
    icon: '📊',
    description: 'OHLCV candle data',
    premium: false,
    inputs: ['market'],
    outputs: ['candles'],
    defaultData: { timeframe: 'H1' },
  },
  {
    type: 'newsFeed',
    label: 'News Feed',
    category: 'source',
    icon: '📰',
    description: 'Forex news & headlines',
    premium: false,
    inputs: [],
    outputs: ['news'],
    defaultData: {},
  },
  {
    type: 'economicCalendar',
    label: 'Economic Calendar',
    category: 'source',
    icon: '📅',
    description: 'NFP, FOMC, ECB, BOJ events',
    premium: false,
    inputs: [],
    outputs: ['events'],
    defaultData: {},
  },

  // Analysis
  {
    type: 'technicalIndicator',
    label: 'Technical Indicators',
    category: 'analysis',
    icon: '📈',
    description: 'RSI, MACD, Bollinger, EMA, SMA',
    premium: false,
    inputs: ['candles'],
    outputs: ['signals'],
    defaultData: { indicators: ['RSI', 'MACD', 'Bollinger Bands'] },
  },
  {
    type: 'chartPattern',
    label: 'Chart Patterns',
    category: 'analysis',
    icon: '🔍',
    description: 'Double Top, H&S, Triangle detection',
    premium: false,
    inputs: ['candles'],
    outputs: ['patterns'],
    defaultData: { patterns: ['Head & Shoulders', 'Double Top', 'Triangle'] },
  },
  {
    type: 'sentiment',
    label: 'Sentiment Analysis',
    category: 'analysis',
    icon: '🧠',
    description: 'Fear & Greed, social sentiment',
    premium: false,
    inputs: ['news'],
    outputs: ['sentiment'],
    defaultData: {},
  },
  {
    type: 'fundamental',
    label: 'Fundamental Analysis',
    category: 'analysis',
    icon: '🏦',
    description: 'Interest rates, GDP, CPI data',
    premium: false,
    inputs: ['events'],
    outputs: ['analysis'],
    defaultData: {},
  },
  {
    type: 'psychProfile',
    label: 'Risk Profile',
    category: 'analysis',
    icon: '🎯',
    description: 'Trading style & risk tolerance',
    premium: false,
    inputs: [],
    outputs: ['profile'],
    defaultData: { riskTolerance: 'moderate', style: 'swing' },
  },

  {
    type: 'stockAnalysis',
    label: 'Stock Analyzer',
    category: 'analysis',
    icon: '🏛️',
    description: 'P/E, FCF, EBITDA, мультипликаторы',
    premium: false,
    inputs: ['data'],
    outputs: ['analysis'],
    defaultData: { ticker: 'SBER' },
  },
  {
    type: 'reportSelector',
    label: 'Report Type',
    category: 'analysis',
    icon: '📊',
    description: 'РСБУ vs МСФО — какой отчёт для чего',
    premium: false,
    inputs: ['data'],
    outputs: ['report'],
    defaultData: {},
  },
  {
    type: 'cashFlow',
    label: 'Cash Flow',
    category: 'analysis',
    icon: '💰',
    description: 'FCF, EBITDA, CAPEX, LTM',
    premium: false,
    inputs: ['data'],
    outputs: ['cashflow'],
    defaultData: {},
  },
  {
    type: 'debtAnalysis',
    label: 'Debt Analysis',
    category: 'analysis',
    icon: '📉',
    description: 'Долговая нагрузка, стресс-тест',
    premium: false,
    inputs: ['data'],
    outputs: ['debt'],
    defaultData: {},
  },
  {
    type: 'sectorCompare',
    label: 'Sector Compare',
    category: 'analysis',
    icon: '🏭',
    description: 'Лучшая компания в отрасли',
    premium: false,
    inputs: ['data'],
    outputs: ['sector'],
    defaultData: {},
  },
  {
    type: 'profitability',
    label: 'Profitability',
    category: 'analysis',
    icon: '📈',
    description: 'ROE, ROA, маржинальность',
    premium: false,
    inputs: ['data'],
    outputs: ['profit'],
    defaultData: {},
  },
  {
    type: 'dividendCapture',
    label: 'Dividend Capture',
    category: 'analysis',
    icon: '💎',
    description: 'Дивидоходность, отсечка, payout',
    premium: false,
    inputs: ['data'],
    outputs: ['dividends'],
    defaultData: {},
  },
  {
    type: 'eventRepricing',
    label: 'Event Repricing',
    category: 'analysis',
    icon: '📰',
    description: 'Переоценка после отчётов и событий',
    premium: false,
    inputs: ['data'],
    outputs: ['events'],
    defaultData: {},
  },
  {
    type: 'tradingStyle',
    label: 'Trading Style',
    category: 'agent',
    icon: '🎯',
    description: 'Скальпинг, свинг или долгосрок',
    premium: false,
    inputs: ['analysis'],
    outputs: ['style'],
    defaultData: { tradingStyle: 'swing' },
  },
  {
    type: 'portfolioScore',
    label: 'Portfolio Score',
    category: 'output',
    icon: '🎯',
    description: 'Итоговый скоринг: брать или нет',
    premium: false,
    inputs: ['analysis', 'cashflow', 'debt', 'sector', 'profit'],
    outputs: [],
    defaultData: {},
  },

  // Logic
  {
    type: 'condition',
    label: 'Condition',
    category: 'logic',
    icon: '⚡',
    description: 'If/then rules',
    premium: false,
    inputs: ['signals'],
    outputs: ['trigger'],
    defaultData: { indicator: 'RSI', operator: '>', value: 70 },
  },
  {
    type: 'combiner',
    label: 'Combiner',
    category: 'logic',
    icon: '🔗',
    description: 'AND / OR logic',
    premium: false,
    inputs: ['input1', 'input2'],
    outputs: ['combined'],
    defaultData: { logic: 'AND' },
  },

  // AI Agents
  {
    type: 'tradingAnalyst',
    label: 'Trading Analyst',
    category: 'agent',
    icon: '🤖',
    description: 'AI analyzes all inputs',
    premium: false,
    inputs: ['signals', 'news', 'patterns'],
    outputs: ['analysis'],
    defaultData: { prompt: 'Analyze the current market conditions' },
  },
  {
    type: 'riskManager',
    label: 'Risk Manager',
    category: 'agent',
    icon: '🛡️',
    description: 'AI risk assessment',
    premium: false,
    inputs: ['analysis', 'profile'],
    outputs: ['risk'],
    defaultData: { prompt: 'Evaluate risk for this strategy' },
  },
  {
    type: 'guidedTrader',
    label: 'Guided AI',
    category: 'agent',
    icon: '🎓',
    description: 'Explains WHY — for beginners',
    premium: false,
    inputs: ['signals', 'news'],
    outputs: ['analysis'],
    defaultData: { level: 'beginner' },
  },
  {
    type: 'riskCap',
    label: 'Risk Cap',
    category: 'agent',
    icon: '🔥',
    description: 'Daily loss & trade limits',
    premium: false,
    inputs: ['analysis'],
    outputs: ['risk'],
    defaultData: { maxDailyLoss: 500, maxPositionSize: 0.5, maxTradesPerDay: 10 },
  },

  // Output
  {
    type: 'dashboard',
    label: 'Dashboard',
    category: 'output',
    icon: '📋',
    description: 'Visual output & signals',
    premium: false,
    inputs: ['analysis', 'risk'],
    outputs: [],
    defaultData: { widgets: ['gauge', 'signals', 'chart'] },
  },
];

export const CATEGORY_LABELS: Record<string, { label: string; color: string }> = {
  source: { label: 'Sources', color: '#3b82f6' },
  analysis: { label: 'Analysis', color: '#10b981' },
  logic: { label: 'Logic', color: '#f59e0b' },
  agent: { label: 'AI Agents', color: '#a855f7' },
  output: { label: 'Output', color: '#ef4444' },
};
